import { PrismaClient, Difficulty } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seeding database...')

  // Create 3 demo users
  const [alice, bob, carol] = await Promise.all([
    prisma.user.upsert({
      where: { email: 'alice@cookbook.dev' },
      update: {},
      create: {
        email: 'alice@cookbook.dev',
        passwordHash: await bcrypt.hash('password123', 12),
        fullName: 'Alice Chen',
        displayName: 'Alice Chen',
        avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
        bio: 'Home cook passionate about Asian fusion cuisine.',
      },
    }),
    prisma.user.upsert({
      where: { email: 'bob@cookbook.dev' },
      update: {},
      create: {
        email: 'bob@cookbook.dev',
        passwordHash: await bcrypt.hash('password123', 12),
        fullName: 'Bob Martinez',
        displayName: 'Bob Martinez',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
        bio: 'BBQ enthusiast and weekend grill master.',
      },
    }),
    prisma.user.upsert({
      where: { email: 'carol@cookbook.dev' },
      update: {},
      create: {
        email: 'carol@cookbook.dev',
        passwordHash: await bcrypt.hash('password123', 12),
        fullName: 'Carol Williams',
        displayName: 'Carol Williams',
        avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100',
        bio: 'Pastry chef and dessert lover.',
      },
    }),
  ])

  const recipes = [
    {
      title: 'Classic Eggs Benedict',
      description: 'Perfectly poached eggs on toasted English muffins with Canadian bacon and hollandaise sauce.',
      imageUrl: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=800',
      authorId: alice.id,
      authorName: alice.displayName!,
      authorAvatar: alice.avatarUrl,
      prepTime: '30 min',
      difficulty: Difficulty.Medium,
      category: 'Breakfast',
      servings: 2,
      calories: 520,
      popular: true,
      rating: 4.8,
      reviewsCount: 142,
      youtubeId: 'RqA2N0rVaKQ',
      ingredients: [
        '4 large eggs',
        '2 English muffins, split and toasted',
        '4 slices Canadian bacon',
        '2 tablespoons white wine vinegar',
        '3 egg yolks for hollandaise',
        '1/2 cup clarified butter',
        'Juice of half a lemon',
        'Salt and white pepper to taste',
        'Fresh chives for garnish',
      ],
      instructions: [
        'Prepare hollandaise: whisk egg yolks with lemon juice over a double boiler until thick.',
        'Slowly drizzle in warm clarified butter while whisking continuously.',
        'Season hollandaise with salt and white pepper, keep warm.',
        'Bring a wide saucepan of water to a gentle simmer, add vinegar.',
        'Crack eggs into individual cups, then gently slide into simmering water.',
        'Poach eggs for 3–4 minutes until whites are set but yolks are runny.',
        'Toast English muffins and place Canadian bacon on each half.',
        'Top each muffin half with a poached egg and a generous spoon of hollandaise.',
      ],
      nutrition: [
        { label: 'Calories', value: '520 kcal' },
        { label: 'Protein', value: '24g' },
        { label: 'Fat', value: '38g' },
        { label: 'Carbs', value: '22g' },
        { label: 'Sodium', value: '820mg' },
      ],
      tags: ['breakfast', 'eggs', 'brunch', 'classic'],
    },
    {
      title: 'Avocado Toast with Poached Egg',
      description: 'Creamy smashed avocado on sourdough toast topped with a perfectly poached egg and everything bagel seasoning.',
      imageUrl: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c820?w=800',
      authorId: alice.id,
      authorName: alice.displayName!,
      authorAvatar: alice.avatarUrl,
      prepTime: '15 min',
      difficulty: Difficulty.Easy,
      category: 'Breakfast',
      servings: 2,
      calories: 350,
      popular: true,
      rating: 4.6,
      reviewsCount: 98,
      ingredients: [
        '2 slices sourdough bread, toasted',
        '1 ripe avocado',
        '2 large eggs',
        'Juice of half a lemon',
        '1 tablespoon white vinegar',
        'Everything bagel seasoning',
        'Red pepper flakes',
        'Salt and black pepper',
        'Fresh microgreens for garnish',
      ],
      instructions: [
        'Toast sourdough slices until golden and crisp.',
        'Halve, pit, and scoop avocado into a bowl.',
        'Mash with lemon juice, salt, and pepper until creamy but chunky.',
        'Bring a small saucepan of water to simmer, add vinegar.',
        'Poach eggs for 3 minutes until whites are just set.',
        'Spread mashed avocado on toast, top with poached egg.',
        'Sprinkle with everything bagel seasoning and red pepper flakes.',
      ],
      nutrition: [
        { label: 'Calories', value: '350 kcal' },
        { label: 'Protein', value: '14g' },
        { label: 'Fat', value: '22g' },
        { label: 'Carbs', value: '28g' },
        { label: 'Fiber', value: '7g' },
      ],
      tags: ['breakfast', 'healthy', 'avocado', 'vegan-friendly'],
    },
    {
      title: 'Grilled Salmon with Lemon Dill Sauce',
      description: 'Perfectly grilled salmon fillets with a bright lemon dill cream sauce, served with roasted asparagus.',
      imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800',
      authorId: bob.id,
      authorName: bob.displayName!,
      authorAvatar: bob.avatarUrl,
      prepTime: '25 min',
      difficulty: Difficulty.Medium,
      category: 'Seafood',
      servings: 4,
      calories: 420,
      popular: true,
      rating: 4.9,
      reviewsCount: 203,
      youtubeId: 'Y5jKAL0eZuY',
      ingredients: [
        '4 salmon fillets (6 oz each)',
        '2 tablespoons olive oil',
        '2 garlic cloves, minced',
        'Zest and juice of 1 lemon',
        '3 tablespoons fresh dill, chopped',
        '1/2 cup heavy cream',
        '1 bunch asparagus, trimmed',
        'Salt and black pepper',
        'Capers for garnish',
      ],
      instructions: [
        'Pat salmon dry and season generously with salt and pepper.',
        'Brush with olive oil and press garlic onto flesh side.',
        'Preheat grill or grill pan to medium-high heat.',
        'Grill salmon skin-side down for 4–5 minutes, flip once.',
        'Cook 3–4 minutes more until salmon flakes easily.',
        'Toss asparagus with oil, salt, and pepper; grill alongside salmon.',
        'Simmer cream, lemon zest, lemon juice, and dill for 2 minutes.',
        'Plate salmon over asparagus and drizzle with lemon dill sauce.',
      ],
      nutrition: [
        { label: 'Calories', value: '420 kcal' },
        { label: 'Protein', value: '42g' },
        { label: 'Fat', value: '26g' },
        { label: 'Carbs', value: '6g' },
        { label: 'Omega-3', value: '2.5g' },
      ],
      tags: ['seafood', 'grilled', 'healthy', 'dinner'],
    },
    {
      title: 'Chocolate Lava Cake',
      description: 'Decadent individual chocolate cakes with a warm, gooey molten center. Perfect for dinner parties.',
      imageUrl: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=800',
      authorId: carol.id,
      authorName: carol.displayName!,
      authorAvatar: carol.avatarUrl,
      prepTime: '20 min',
      difficulty: Difficulty.Medium,
      category: 'Desserts',
      servings: 4,
      calories: 480,
      popular: true,
      rating: 4.9,
      reviewsCount: 317,
      ingredients: [
        '170g dark chocolate (70%), chopped',
        '115g unsalted butter, plus more for ramekins',
        '3 large eggs',
        '3 egg yolks',
        '90g powdered sugar',
        '50g all-purpose flour',
        '1 teaspoon vanilla extract',
        'Pinch of sea salt',
        'Vanilla ice cream to serve',
        'Cocoa powder for dusting',
      ],
      instructions: [
        'Preheat oven to 220°C (425°F). Butter four 6-oz ramekins and dust with cocoa powder.',
        'Melt chocolate and butter together in a heatproof bowl over simmering water; stir until smooth.',
        'Remove from heat, whisk in powdered sugar until combined.',
        'Beat in eggs and egg yolks one at a time, then add vanilla.',
        'Fold in flour and salt until just combined.',
        'Divide batter evenly among prepared ramekins.',
        'Bake 11–12 minutes until edges are firm but center jiggles slightly.',
        'Run a knife around edges, invert onto plates, and serve immediately with ice cream.',
      ],
      nutrition: [
        { label: 'Calories', value: '480 kcal' },
        { label: 'Fat', value: '32g' },
        { label: 'Carbs', value: '44g' },
        { label: 'Protein', value: '8g' },
        { label: 'Sugar', value: '34g' },
      ],
      tags: ['dessert', 'chocolate', 'baking', 'indulgent'],
    },
    {
      title: 'Chicken Caesar Salad',
      description: 'Crisp romaine lettuce, grilled chicken, house-made caesar dressing, parmesan, and crunchy croutons.',
      imageUrl: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800',
      authorId: alice.id,
      authorName: alice.displayName!,
      authorAvatar: alice.avatarUrl,
      prepTime: '20 min',
      difficulty: Difficulty.Easy,
      category: 'Lunch',
      servings: 2,
      calories: 380,
      rating: 4.5,
      reviewsCount: 88,
      ingredients: [
        '2 chicken breasts',
        '1 large head romaine lettuce, chopped',
        '1/2 cup grated Parmesan',
        '1 cup croutons',
        '2 tablespoons olive oil',
        '2 garlic cloves, minced',
        '1 tablespoon Dijon mustard',
        '2 tablespoons lemon juice',
        '1 teaspoon Worcestershire sauce',
        '1/3 cup mayonnaise',
      ],
      instructions: [
        'Season chicken with olive oil, salt, and pepper.',
        'Grill or pan-sear over medium-high heat for 6–7 minutes per side.',
        'Rest 5 minutes then slice against the grain.',
        'Whisk together garlic, Dijon, lemon juice, Worcestershire, and mayonnaise for dressing.',
        'Toss romaine with dressing until well coated.',
        'Top with sliced chicken, Parmesan shavings, and croutons.',
      ],
      nutrition: [
        { label: 'Calories', value: '380 kcal' },
        { label: 'Protein', value: '38g' },
        { label: 'Fat', value: '18g' },
        { label: 'Carbs', value: '16g' },
        { label: 'Fiber', value: '3g' },
      ],
      tags: ['lunch', 'salad', 'chicken', 'classic'],
    },
    {
      title: 'Vegetable Stir-Fry with Tofu',
      description: 'Colorful crispy vegetables and golden tofu in a savory ginger-garlic soy sauce over steamed jasmine rice.',
      imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800',
      authorId: alice.id,
      authorName: alice.displayName!,
      authorAvatar: alice.avatarUrl,
      prepTime: '30 min',
      difficulty: Difficulty.Easy,
      category: 'Vegetarian',
      servings: 3,
      calories: 320,
      rating: 4.4,
      reviewsCount: 72,
      ingredients: [
        '400g firm tofu, pressed and cubed',
        '2 cups broccoli florets',
        '1 red bell pepper, sliced',
        '1 cup snap peas',
        '2 carrots, julienned',
        '3 garlic cloves, minced',
        '1 tablespoon fresh ginger, grated',
        '3 tablespoons soy sauce',
        '1 tablespoon sesame oil',
        '2 tablespoons vegetable oil',
        '1 tablespoon cornstarch',
        'Sesame seeds and spring onions to serve',
      ],
      instructions: [
        'Pat tofu dry, cube, and toss with 1 tablespoon soy sauce and cornstarch.',
        'Pan-fry tofu in vegetable oil until golden and crispy on all sides; set aside.',
        'Stir-fry garlic and ginger in remaining oil for 30 seconds.',
        'Add harder vegetables (carrots, broccoli) and stir-fry 3 minutes.',
        'Add bell pepper and snap peas; cook 2 minutes more.',
        'Pour in remaining soy sauce and sesame oil; toss to coat.',
        'Return tofu to wok, toss gently, serve over rice with sesame seeds.',
      ],
      nutrition: [
        { label: 'Calories', value: '320 kcal' },
        { label: 'Protein', value: '18g' },
        { label: 'Fat', value: '16g' },
        { label: 'Carbs', value: '28g' },
        { label: 'Fiber', value: '6g' },
      ],
      tags: ['vegetarian', 'vegan', 'asian', 'healthy'],
    },
    {
      title: 'BBQ Smash Burgers',
      description: 'Crispy-edged smash burgers with melted American cheese, pickles, and secret sauce on brioche buns.',
      imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800',
      authorId: bob.id,
      authorName: bob.displayName!,
      authorAvatar: bob.avatarUrl,
      prepTime: '20 min',
      difficulty: Difficulty.Easy,
      category: 'Dinner',
      servings: 4,
      calories: 680,
      popular: false,
      rating: 4.7,
      reviewsCount: 156,
      ingredients: [
        '600g 80/20 ground beef, divided into 4 balls',
        '4 brioche burger buns',
        '4 slices American cheese',
        '1/2 cup mayonnaise',
        '2 tablespoons ketchup',
        '1 tablespoon yellow mustard',
        '1 teaspoon hot sauce',
        'Dill pickle slices',
        'Shredded iceberg lettuce',
        'Sliced white onion',
        'Salt and black pepper',
      ],
      instructions: [
        'Mix mayo, ketchup, mustard, and hot sauce for secret sauce; refrigerate.',
        'Heat a cast iron skillet or flat-top grill over high heat until smoking.',
        'Place beef ball on hot surface, smash firmly with a spatula to thin patty.',
        'Season with salt and pepper immediately after smashing.',
        'Cook 2 minutes until dark crust forms; flip once.',
        'Immediately place cheese on patty; cook 1 minute.',
        'Toast buns cut-side down until golden.',
        'Assemble: sauce on both buns, patty, pickles, onion, and lettuce.',
      ],
      nutrition: [
        { label: 'Calories', value: '680 kcal' },
        { label: 'Protein', value: '36g' },
        { label: 'Fat', value: '42g' },
        { label: 'Carbs', value: '38g' },
        { label: 'Sodium', value: '980mg' },
      ],
      tags: ['burger', 'beef', 'bbq', 'dinner'],
    },
    {
      title: 'Strawberry Cheesecake',
      description: 'Creamy New York-style cheesecake with a buttery graham cracker crust and fresh strawberry topping.',
      imageUrl: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=800',
      authorId: carol.id,
      authorName: carol.displayName!,
      authorAvatar: carol.avatarUrl,
      prepTime: '90 min',
      difficulty: Difficulty.Hard,
      category: 'Desserts',
      servings: 12,
      calories: 420,
      rating: 4.8,
      reviewsCount: 264,
      ingredients: [
        '200g graham crackers, crushed',
        '80g unsalted butter, melted',
        '900g cream cheese, room temperature',
        '200g granulated sugar',
        '3 large eggs',
        '1 teaspoon vanilla extract',
        '240ml sour cream',
        '2 tablespoons all-purpose flour',
        '500g fresh strawberries',
        '3 tablespoons strawberry jam',
        'Zest of 1 lemon',
      ],
      instructions: [
        'Preheat oven to 160°C (325°F). Mix crushed crackers with melted butter; press into 9-inch springform pan.',
        'Bake crust 10 minutes; cool completely.',
        'Beat cream cheese until smooth, add sugar gradually.',
        'Add eggs one at a time, beating on low after each addition.',
        'Mix in vanilla, lemon zest, sour cream, and flour.',
        'Pour over cooled crust, tap to remove bubbles.',
        'Bake in a water bath for 60–70 minutes until just set; center will jiggle slightly.',
        'Cool in oven with door ajar 1 hour, then refrigerate overnight.',
        'Top with strawberries glazed with warmed jam before serving.',
      ],
      nutrition: [
        { label: 'Calories', value: '420 kcal' },
        { label: 'Fat', value: '29g' },
        { label: 'Carbs', value: '33g' },
        { label: 'Protein', value: '7g' },
        { label: 'Sugar', value: '24g' },
      ],
      tags: ['dessert', 'cheesecake', 'baking', 'strawberry'],
    },
    {
      title: 'Mango Lassi',
      description: 'Refreshing Indian yogurt drink blended with sweet Alphonso mangoes, cardamom, and a hint of rose water.',
      imageUrl: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=800',
      authorId: alice.id,
      authorName: alice.displayName!,
      authorAvatar: alice.avatarUrl,
      prepTime: '10 min',
      difficulty: Difficulty.Easy,
      category: 'Drinks',
      servings: 2,
      calories: 210,
      rating: 4.6,
      reviewsCount: 55,
      ingredients: [
        '2 ripe mangoes, peeled and chopped (or 400ml canned mango pulp)',
        '240ml plain whole-milk yogurt',
        '120ml cold water or milk',
        '2 tablespoons sugar (adjust to taste)',
        '1/4 teaspoon ground cardamom',
        '1 teaspoon rose water (optional)',
        'Pinch of saffron dissolved in 1 tablespoon warm milk (optional)',
        'Ice cubes',
        'Pistachios for garnish',
      ],
      instructions: [
        'Blend mango, yogurt, water, and sugar until smooth.',
        'Add cardamom and rose water; blend again.',
        'Taste and adjust sweetness.',
        'Pour over ice into tall glasses.',
        'Drizzle saffron milk on top and garnish with crushed pistachios.',
      ],
      nutrition: [
        { label: 'Calories', value: '210 kcal' },
        { label: 'Protein', value: '6g' },
        { label: 'Fat', value: '4g' },
        { label: 'Carbs', value: '38g' },
        { label: 'Vitamin C', value: '45mg' },
      ],
      tags: ['drink', 'smoothie', 'indian', 'mango'],
    },
    {
      title: 'Shrimp Tacos with Mango Salsa',
      description: 'Spicy chipotle-seasoned shrimp in warm corn tortillas topped with sweet mango salsa and lime crema.',
      imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800',
      authorId: bob.id,
      authorName: bob.displayName!,
      authorAvatar: bob.avatarUrl,
      prepTime: '25 min',
      difficulty: Difficulty.Easy,
      category: 'Seafood',
      servings: 4,
      calories: 390,
      rating: 4.7,
      reviewsCount: 133,
      ingredients: [
        '500g large shrimp, peeled and deveined',
        '8 small corn tortillas',
        '1 teaspoon chipotle powder',
        '1 teaspoon cumin',
        '1/2 teaspoon garlic powder',
        '1 mango, diced',
        '1/2 red onion, finely diced',
        '1 jalapeño, seeded and minced',
        'Juice of 2 limes',
        '1/4 cup fresh cilantro',
        '1/3 cup sour cream',
        'Shredded purple cabbage',
      ],
      instructions: [
        'Toss shrimp with chipotle, cumin, garlic powder, salt, and olive oil.',
        'Cook shrimp in hot pan or grill for 2 minutes per side until pink and curled.',
        'Make mango salsa: combine mango, onion, jalapeño, lime juice, and cilantro.',
        'Mix sour cream with remaining lime juice for crema.',
        'Warm tortillas over open flame or dry skillet.',
        'Layer shrimp, cabbage, mango salsa, and drizzle of crema on each tortilla.',
      ],
      nutrition: [
        { label: 'Calories', value: '390 kcal' },
        { label: 'Protein', value: '32g' },
        { label: 'Fat', value: '10g' },
        { label: 'Carbs', value: '44g' },
        { label: 'Fiber', value: '4g' },
      ],
      tags: ['tacos', 'seafood', 'shrimp', 'mexican'],
    },
    {
      title: 'Granola Parfait',
      description: 'Layers of homemade honey-oat granola, thick Greek yogurt, and fresh seasonal berries.',
      imageUrl: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=800',
      authorId: carol.id,
      authorName: carol.displayName!,
      authorAvatar: carol.avatarUrl,
      prepTime: '35 min',
      difficulty: Difficulty.Easy,
      category: 'Breakfast',
      servings: 4,
      calories: 280,
      rating: 4.3,
      reviewsCount: 46,
      ingredients: [
        '2 cups rolled oats',
        '1/2 cup mixed nuts (almonds, pecans), roughly chopped',
        '1/4 cup honey',
        '3 tablespoons coconut oil, melted',
        '1 teaspoon vanilla extract',
        '1/2 teaspoon cinnamon',
        '2 cups Greek yogurt',
        '1 cup fresh mixed berries',
        '2 tablespoons chia seeds',
        'Mint leaves for garnish',
      ],
      instructions: [
        'Preheat oven to 180°C (350°F). Line a baking sheet with parchment.',
        'Mix oats, nuts, honey, coconut oil, vanilla, and cinnamon.',
        'Spread evenly and bake 20–25 minutes, stirring halfway, until golden.',
        'Cool completely; granola will crisp up as it cools.',
        'Layer yogurt, granola, and berries in glasses or bowls.',
        'Sprinkle chia seeds and garnish with mint.',
      ],
      nutrition: [
        { label: 'Calories', value: '280 kcal' },
        { label: 'Protein', value: '14g' },
        { label: 'Fat', value: '10g' },
        { label: 'Carbs', value: '38g' },
        { label: 'Fiber', value: '5g' },
      ],
      tags: ['breakfast', 'healthy', 'granola', 'vegetarian'],
    },
    {
      title: 'Beef Bulgogi Bowl',
      description: 'Tender marinated Korean BBQ beef over steamed rice with pickled vegetables and spicy gochujang sauce.',
      imageUrl: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800',
      authorId: alice.id,
      authorName: alice.displayName!,
      authorAvatar: alice.avatarUrl,
      prepTime: '40 min',
      difficulty: Difficulty.Medium,
      category: 'Dinner',
      servings: 4,
      calories: 550,
      popular: false,
      rating: 4.8,
      reviewsCount: 187,
      ingredients: [
        '600g beef ribeye or sirloin, thinly sliced',
        '4 cups cooked short-grain rice',
        '4 tablespoons soy sauce',
        '2 tablespoons sesame oil',
        '2 tablespoons brown sugar',
        '4 garlic cloves, minced',
        '1 tablespoon fresh ginger, grated',
        '1 Asian pear, grated (for tenderizing)',
        '2 tablespoons gochujang paste',
        '2 spring onions, sliced',
        'Sesame seeds, cucumber, and kimchi to serve',
      ],
      instructions: [
        'Combine soy sauce, sesame oil, brown sugar, garlic, ginger, and grated pear for marinade.',
        'Marinate sliced beef for at least 30 minutes (overnight is best).',
        'Cook marinated beef in a hot wok or grill pan in batches for 2–3 minutes.',
        'Avoid overcrowding to ensure caramelization not steaming.',
        'Mix gochujang with 1 tablespoon sesame oil and a little honey for sauce.',
        'Assemble bowls with rice, bulgogi, cucumber, kimchi, and drizzle of sauce.',
        'Garnish with spring onions and sesame seeds.',
      ],
      nutrition: [
        { label: 'Calories', value: '550 kcal' },
        { label: 'Protein', value: '38g' },
        { label: 'Fat', value: '22g' },
        { label: 'Carbs', value: '48g' },
        { label: 'Iron', value: '4mg' },
      ],
      tags: ['korean', 'beef', 'bowl', 'dinner'],
    },
    {
      title: 'Classic Tonkotsu Ramen',
      description: 'Rich, creamy pork bone broth with handmade noodles and chashu',
      imageUrl: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800',
      authorName: 'Chef Tanaka',
      authorAvatar: 'CT',
      prepTime: '45 min',
      difficulty: Difficulty.Medium,
      category: 'Dinner',
      servings: 4,
      calories: 680,
      popular: true,
      rating: 4.9,
      reviewsCount: 2847,
      youtubeId: 'dH0k0PhFm5g',
      ingredients: [
        '400g pork bones',
        '200g chashu pork belly',
        '4 portions fresh ramen noodles',
        '4 soft-boiled eggs',
        '2 sheets nori',
        '4 tbsp tare sauce',
        'Spring onions, sliced',
        'Sesame seeds',
        'Mayu (black garlic oil)',
        '1L chicken stock',
        '6 cloves garlic',
        '2 tbsp ginger, sliced',
      ],
      instructions: [
        'Blanch pork bones in boiling water for 10 min, then rinse thoroughly.',
        'Simmer bones with garlic and ginger in fresh water for 6-8 hours until milky white.',
        'Prepare chashu by rolling and tying pork belly, then braise in soy, mirin, and sake for 2 hours.',
        'Make soft-boiled eggs: boil 6.5 min, ice bath, peel, then marinate in tare overnight.',
        'Cook ramen noodles according to package — do not overcook, keep al dente.',
        'Assemble: ladle hot broth into bowls with tare, add noodles, top with chashu, egg, nori, and garnish.',
      ],
      nutrition: [
        { label: 'Calories', value: '680 kcal' },
        { label: 'Protein', value: '42g' },
        { label: 'Carbs', value: '58g' },
        { label: 'Fat', value: '28g' },
        { label: 'Fiber', value: '3g' },
        { label: 'Sodium', value: '1200mg' },
      ],
      tags: ['Japanese', 'Soup'],
    },
    {
      title: 'Salmon Poke Bowl',
      description: 'Fresh salmon with avocado, edamame and sesame rice',
      imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
      authorName: 'Mia Chen',
      authorAvatar: 'MC',
      prepTime: '15 min',
      difficulty: Difficulty.Easy,
      category: 'Lunch',
      servings: 2,
      calories: 520,
      popular: true,
      rating: 4.8,
      reviewsCount: 1243,
      youtubeId: 'dH0k0PhFm5g',
      ingredients: [
        '300g sushi-grade salmon',
        '2 cups sushi rice',
        '1 avocado, diced',
        '100g edamame, shelled',
        '2 tbsp soy sauce',
        '1 tbsp sesame oil',
        '1 tbsp rice vinegar',
        'Sesame seeds',
        'Pickled ginger',
        'Nori strips',
      ],
      instructions: [
        'Cook sushi rice and season with rice vinegar, let cool.',
        'Dice salmon into 1cm cubes and toss with soy sauce and sesame oil.',
        'Prepare toppings: dice avocado, shell edamame, slice spring onions.',
        'Assemble bowls with rice base, arrange salmon and toppings.',
        'Garnish with sesame seeds, pickled ginger, and nori strips.',
      ],
      nutrition: [
        { label: 'Calories', value: '520 kcal' },
        { label: 'Protein', value: '35g' },
        { label: 'Carbs', value: '48g' },
        { label: 'Fat', value: '22g' },
        { label: 'Fiber', value: '6g' },
        { label: 'Sodium', value: '680mg' },
      ],
      tags: ['Healthy', 'Quick & Easy'],
    },
    {
      title: 'Chicken Katsu Curry',
      description: 'Crispy panko chicken with rich Japanese curry sauce',
      imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800',
      authorName: 'Kenji Yamada',
      authorAvatar: 'KY',
      prepTime: '35 min',
      difficulty: Difficulty.Medium,
      category: 'Dinner',
      servings: 4,
      calories: 750,
      popular: true,
      rating: 4.7,
      reviewsCount: 986,
      youtubeId: 'dH0k0PhFm5g',
      ingredients: [
        '4 chicken thighs',
        '200g panko breadcrumbs',
        '2 eggs, beaten',
        '100g plain flour',
        'Japanese curry roux blocks',
        '2 potatoes, cubed',
        '2 carrots, sliced',
        '1 onion, diced',
        'Steamed rice',
        'Vegetable oil',
      ],
      instructions: [
        'Flatten chicken thighs, season with salt and pepper.',
        'Dredge in flour, dip in egg, coat in panko breadcrumbs.',
        'Deep fry at 170°C for 6-8 minutes until golden and cooked through.',
        'Sauté onion, carrot, and potato in a pot, add water and simmer until soft.',
        'Add curry roux blocks, stir until dissolved and thickened.',
        'Slice katsu, serve over rice, ladle curry sauce on top.',
      ],
      nutrition: [
        { label: 'Calories', value: '750 kcal' },
        { label: 'Protein', value: '38g' },
        { label: 'Carbs', value: '72g' },
        { label: 'Fat', value: '32g' },
        { label: 'Fiber', value: '5g' },
        { label: 'Sodium', value: '980mg' },
      ],
      tags: ['Japanese', 'Curry'],
    },
    {
      title: 'Caprese Bruschetta',
      description: 'Toasted sourdough with fresh tomatoes, mozzarella and basil',
      imageUrl: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=800',
      authorName: 'Sofia Romano',
      authorAvatar: 'SR',
      prepTime: '10 min',
      difficulty: Difficulty.Easy,
      category: 'Appetizers',
      servings: 4,
      calories: 280,
      popular: false,
      rating: 4.6,
      reviewsCount: 754,
      youtubeId: 'dH0k0PhFm5g',
      ingredients: [
        '1 sourdough baguette',
        '4 ripe tomatoes',
        '200g fresh mozzarella',
        'Fresh basil leaves',
        '2 tbsp extra virgin olive oil',
        '1 clove garlic',
        'Balsamic glaze',
        'Sea salt & pepper',
      ],
      instructions: [
        'Slice baguette diagonally, brush with olive oil, and toast until golden.',
        'Rub warm bread with a cut garlic clove.',
        'Dice tomatoes and season with salt, pepper, and olive oil.',
        'Tear mozzarella into pieces, place on toasted bread with tomatoes.',
        'Top with fresh basil and drizzle with balsamic glaze.',
      ],
      nutrition: [
        { label: 'Calories', value: '280 kcal' },
        { label: 'Protein', value: '12g' },
        { label: 'Carbs', value: '28g' },
        { label: 'Fat', value: '14g' },
        { label: 'Fiber', value: '2g' },
        { label: 'Sodium', value: '420mg' },
      ],
      tags: ['Italian', 'Quick & Easy'],
    },
    {
      title: 'Açaí Power Bowl',
      description: 'Antioxidant-rich açaí blended with banana and topped with granola',
      imageUrl: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800',
      authorName: 'Luna Verde',
      authorAvatar: 'LV',
      prepTime: '10 min',
      difficulty: Difficulty.Easy,
      category: 'Breakfast',
      servings: 1,
      calories: 380,
      popular: true,
      rating: 4.8,
      reviewsCount: 1567,
      youtubeId: 'dH0k0PhFm5g',
      ingredients: [
        '200g frozen açaí pulp',
        '1 banana',
        '100ml almond milk',
        'Granola',
        'Fresh berries',
        'Sliced banana',
        'Coconut flakes',
        'Chia seeds',
        'Honey or agave',
      ],
      instructions: [
        'Blend frozen açaí pulp with banana and almond milk until thick and smooth.',
        'Pour into a bowl — consistency should be thicker than a smoothie.',
        'Top with granola, fresh berries, sliced banana, and coconut flakes.',
        'Drizzle with honey and sprinkle chia seeds.',
      ],
      nutrition: [
        { label: 'Calories', value: '380 kcal' },
        { label: 'Protein', value: '8g' },
        { label: 'Carbs', value: '56g' },
        { label: 'Fat', value: '14g' },
        { label: 'Fiber', value: '9g' },
        { label: 'Sodium', value: '45mg' },
      ],
      tags: ['Healthy', 'Vegan'],
    },
    {
      title: 'Spaghetti Carbonara',
      description: 'Authentic Roman carbonara with guanciale and pecorino',
      imageUrl: 'https://images.unsplash.com/photo-1588013273468-315fd88ea34c?w=800',
      authorName: 'Marco Bianchi',
      authorAvatar: 'MB',
      prepTime: '20 min',
      difficulty: Difficulty.Medium,
      category: 'Dinner',
      servings: 4,
      calories: 620,
      popular: true,
      rating: 4.9,
      reviewsCount: 3102,
      youtubeId: 'dH0k0PhFm5g',
      ingredients: [
        '400g spaghetti',
        '200g guanciale',
        '4 egg yolks + 2 whole eggs',
        '100g pecorino romano, grated',
        '50g parmigiano reggiano, grated',
        'Freshly cracked black pepper',
      ],
      instructions: [
        'Cook spaghetti in heavily salted water until al dente.',
        'Cut guanciale into thick strips and render in a cold pan over medium heat until crispy.',
        'Whisk egg yolks, whole eggs, and grated cheeses together in a bowl.',
        'Toss hot pasta into guanciale pan (off heat), then quickly add egg mixture.',
        'Toss vigorously — the residual heat creates a creamy sauce. Add pasta water if needed.',
        'Finish with generous black pepper and extra pecorino.',
      ],
      nutrition: [
        { label: 'Calories', value: '620 kcal' },
        { label: 'Protein', value: '28g' },
        { label: 'Carbs', value: '65g' },
        { label: 'Fat', value: '26g' },
        { label: 'Fiber', value: '2g' },
        { label: 'Sodium', value: '850mg' },
      ],
      tags: ['Italian', 'Pasta'],
    },
    {
      title: 'Mediterranean Salad',
      description: 'Crisp vegetables with feta, olives and herb vinaigrette',
      imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800',
      authorName: 'Elena Papadopoulos',
      authorAvatar: 'EP',
      prepTime: '10 min',
      difficulty: Difficulty.Easy,
      category: 'Salads',
      servings: 4,
      calories: 320,
      popular: false,
      rating: 4.5,
      reviewsCount: 612,
      youtubeId: 'dH0k0PhFm5g',
      ingredients: [
        '2 cucumbers',
        '4 tomatoes',
        '1 red onion',
        '200g feta cheese',
        '100g Kalamata olives',
        '1 green bell pepper',
        '3 tbsp extra virgin olive oil',
        '1 tbsp red wine vinegar',
        'Dried oregano',
        'Sea salt',
      ],
      instructions: [
        'Chop cucumbers, tomatoes, and bell pepper into chunks.',
        'Slice red onion into thin rings.',
        'Combine vegetables in a large bowl with olives.',
        'Whisk olive oil, red wine vinegar, oregano, and salt for dressing.',
        'Pour dressing over salad, top with a block of feta cheese.',
      ],
      nutrition: [
        { label: 'Calories', value: '320 kcal' },
        { label: 'Protein', value: '10g' },
        { label: 'Carbs', value: '18g' },
        { label: 'Fat', value: '24g' },
        { label: 'Fiber', value: '4g' },
        { label: 'Sodium', value: '680mg' },
      ],
      tags: ['Healthy', 'Gluten-Free'],
    },
    {
      title: 'Molten Chocolate Cake',
      description: 'Decadent chocolate lava cake with vanilla bean ice cream',
      imageUrl: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=800',
      authorName: 'Amélie Dupont',
      authorAvatar: 'AD',
      prepTime: '25 min',
      difficulty: Difficulty.Medium,
      category: 'Desserts',
      servings: 4,
      calories: 480,
      popular: true,
      rating: 4.8,
      reviewsCount: 1890,
      youtubeId: 'dH0k0PhFm5g',
      ingredients: [
        '200g dark chocolate (70%)',
        '100g unsalted butter',
        '2 eggs + 2 egg yolks',
        '60g sugar',
        '30g plain flour',
        'Pinch of salt',
        'Vanilla bean ice cream',
        'Cocoa powder for dusting',
      ],
      instructions: [
        'Preheat oven to 220°C. Grease and flour 4 ramekins.',
        'Melt chocolate and butter together, stir until smooth.',
        'Whisk eggs, yolks, and sugar until pale and thick.',
        'Fold chocolate mixture into egg mixture, then fold in flour and salt.',
        'Divide batter among ramekins and bake for 12-14 minutes.',
        'Let rest 1 minute, invert onto plates, serve with ice cream immediately.',
      ],
      nutrition: [
        { label: 'Calories', value: '480 kcal' },
        { label: 'Protein', value: '8g' },
        { label: 'Carbs', value: '38g' },
        { label: 'Fat', value: '34g' },
        { label: 'Fiber', value: '3g' },
        { label: 'Sodium', value: '120mg' },
      ],
      tags: ['Dessert', 'Chocolate'],
    },
    {
      title: 'Thai Green Curry',
      description: 'Fragrant coconut curry with Thai basil and jasmine rice',
      imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800',
      authorName: 'Siri Phan',
      authorAvatar: 'SP',
      prepTime: '30 min',
      difficulty: Difficulty.Medium,
      category: 'Dinner',
      servings: 3,
      calories: 550,
      popular: false,
      rating: 4.7,
      reviewsCount: 1045,
      youtubeId: 'dH0k0PhFm5g',
      ingredients: [
        '400ml coconut milk',
        '3 tbsp green curry paste',
        '300g chicken thigh',
        '1 Thai eggplant',
        '100g bamboo shoots',
        'Thai basil leaves',
        '2 kaffir lime leaves',
        '1 tbsp fish sauce',
        '1 tsp palm sugar',
        'Jasmine rice',
        'Red chili for garnish',
      ],
      instructions: [
        'Heat thick coconut cream in a wok until oil separates.',
        'Fry green curry paste in the cream for 2 minutes until fragrant.',
        'Add sliced chicken and cook for 3-4 minutes.',
        'Pour in remaining coconut milk, add eggplant and bamboo shoots.',
        'Season with fish sauce and palm sugar, simmer 10 minutes.',
        'Add kaffir lime leaves and Thai basil, serve over jasmine rice.',
      ],
      nutrition: [
        { label: 'Calories', value: '550 kcal' },
        { label: 'Protein', value: '32g' },
        { label: 'Carbs', value: '42g' },
        { label: 'Fat', value: '28g' },
        { label: 'Fiber', value: '4g' },
        { label: 'Sodium', value: '920mg' },
      ],
      tags: ['Thai', 'Curry'],
    },
    {
      title: 'Baja Fish Tacos',
      description: 'Grilled fish with mango salsa, lime crema and fresh cilantro',
      imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800',
      authorName: 'Carlos Mendez',
      authorAvatar: 'CM',
      prepTime: '20 min',
      difficulty: Difficulty.Easy,
      category: 'Lunch',
      servings: 4,
      calories: 420,
      popular: false,
      rating: 4.6,
      reviewsCount: 823,
      youtubeId: 'dH0k0PhFm5g',
      ingredients: [
        '500g white fish fillets',
        '8 small flour tortillas',
        '1 mango, diced',
        '1 avocado',
        'Lime crema (sour cream + lime juice)',
        'Fresh cilantro',
        'Red cabbage, shredded',
        '1 jalapeño',
        'Lime wedges',
        'Cumin & chili powder',
      ],
      instructions: [
        'Season fish with cumin, chili powder, salt, and pepper.',
        'Grill or pan-fry fish for 3-4 minutes per side until flaky.',
        'Mix diced mango with cilantro, jalapeño, and lime juice for salsa.',
        'Warm tortillas on a dry pan.',
        'Assemble: shredded cabbage, fish, mango salsa, avocado slices.',
        'Drizzle with lime crema and serve with lime wedges.',
      ],
      nutrition: [
        { label: 'Calories', value: '420 kcal' },
        { label: 'Protein', value: '28g' },
        { label: 'Carbs', value: '38g' },
        { label: 'Fat', value: '18g' },
        { label: 'Fiber', value: '5g' },
        { label: 'Sodium', value: '580mg' },
      ],
      tags: ['Mexican', 'Quick & Easy'],
    },
  ]

  // Clear existing data in dependency order
  await prisma.favorite.deleteMany()
  await prisma.comment.deleteMany()
  await prisma.tag.deleteMany()
  await prisma.nutrition.deleteMany()
  await prisma.instruction.deleteMany()
  await prisma.ingredient.deleteMany()
  await prisma.recipe.deleteMany()

  const createdRecipes = []
  for (const r of recipes) {
    const { ingredients, instructions, nutrition, tags, ...recipeData } = r
    const recipe = await prisma.recipe.create({
      data: {
        ...recipeData,
        ingredients: {
          create: ingredients.map((item, i) => ({ item, position: i })),
        },
        instructions: {
          create: instructions.map((step, i) => ({ step, position: i })),
        },
        nutrition: { create: nutrition },
        tags: { create: tags.map((tag) => ({ tag })) },
      },
    })
    createdRecipes.push(recipe)
  }

  // Create some favorites
  await prisma.favorite.createMany({
    data: [
      { userId: alice.id, recipeId: createdRecipes[2].id },
      { userId: alice.id, recipeId: createdRecipes[3].id },
      { userId: bob.id, recipeId: createdRecipes[0].id },
      { userId: bob.id, recipeId: createdRecipes[3].id },
      { userId: carol.id, recipeId: createdRecipes[2].id },
    ],
  })

  console.log(`✅ Seeded ${createdRecipes.length} recipes and 3 users`)
  console.log('Demo credentials: alice@cookbook.dev / password123')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
